### ISSUE TITLE
如何利用netlink批量传递结构体呢

### ISSUE THREAD

**Issue by mebuis** [Seaworth/hello-netlink#3]
哈哈哈，看你代码，风格像是面向GPT编程啊~~哈哈哈，不错

**Comment by Seaworth** [comment]
可以参考struct [nla_policy](https://elixir.bootlin.com/linux/v5.4.188/C/ident/nla_policy)中**NLA_EXACT_LEN**这种类型，可以传递struct mystruct。其中NLA_BINARY用来传递结构体应该也是可以的，只是需要强转为对应的结构体。
 * Example:
 * static const struct nla_policy my_policy[ATTR_MAX+1] = {
 * 	[ATTR_FOO] = { .type = NLA_U16 },
 *	[ATTR_BAR] = { .type = NLA_STRING, .len = BARSIZ },
 *	[ATTR_BAZ] = { .type = **NLA_EXACT_LEN**, .len = sizeof(struct mystruct) },
 *	[ATTR_GOO] = { .type = NLA_BITFIELD32, .validation_data = &myvalidflags },
 * };
